version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - C:/my_docker_volumes/postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "8082:80"
    volumes:
      - C:/my_docker_volumes/pgadmin:/var/lib/pgadmin/data
    depends_on:
      - postgres
    networks:
      - postgres_network
    restart: unless-stopped

networks:
  postgres_network:
    driver: bridge
